CREATE TABLE Accounts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    AccountName VARCHAR(50) NOT NULL,
    AccountType ENUM('CHECKING', 'SAVINGS', 'CREDIT', 'INVESTMENT') NOT NULL,
    Balance DECIMAL(10, 2) NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);
